### ISSUE TITLE
Unable to find step: "nonexistent step name ..."

### ISSUE THREAD

**Issue by james-callahan** [joshdk/drone-github-comment#21] opened 2022-08-31 06:59 UTC
This plugin seems to fail at finding a previous step, showing an error like:

> joshdk/drone-github-comment: nonexistent step name x/y+z

Where my `settings.step` is in the format of `foo/bar+qux`

**Comment by joshdk** [comment] 2022-08-31 16:12
This is _technically_ working as intended. When you specify a step name with a slash in it, it then searches for a step named `bar+qux` inside a stage named `foo`. This is mentioned in the documentation:

> You can either specify both the stage/step name, like `build-pull-request/lint-code` in the example below, or just the step name for convenience.
https://github.com/joshdk/drone-github-comment#usage

The workaround should be to specify both the stage and step name like `my-pipeline/foo/bar+qux`. This did not initially work, but was fixed by #22.

Please try the [new v0.3.0 release](https://github.com/joshdk/drone-github-comment/releases/tag/v0.3.0) which contains this fix. Thank you!

**Closed by joshdk** 2022-08-31 16:12 UTC
